# Generated by Django 4.2.13 on 2024-06-23 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 8, 20, 43, 30, 460610, tzinfo=datetime.timezone.utc)),
        ),
    ]
