# Generated by Django 4.2.13 on 2024-06-23 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_loan_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 8, 20, 44, 43, 542240, tzinfo=datetime.timezone.utc)),
        ),
    ]
