# Generated by Django 4.2.13 on 2024-06-27 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_loan_expected_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrowed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 12, 23, 14, 45, 728890, tzinfo=datetime.timezone.utc)),
        ),
    ]
