# Generated by Django 4.2.13 on 2024-06-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourbookuser',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
